Update Automation.yml

diff --git a/.github/workflows/Automation.yml b/.github/workflows/Automation.yml
--- a/.github/workflows/Automation.yml
+++ b/.github/workflows/Automation.yml
@@ -13,24 +13,25 @@ jobs:
 
     - name: Trigger Jenkins Pipeline with Crumb
       env:
-        JENKINS_URL: https://9c60-103-167-176-239.ngrok-free.app/job/Test/buildWithParameters
-        JENKINS_CRUMB_URL: https://9c60-103-167-176-239.ngrok-free.app/crumbIssuer/api/json
+        JENKINS_URL: https://d8ff-103-167-176-239.ngrok-free.app/job/Test/buildWithParameters
+        JENKINS_CRUMB_URL: https://d8ff-103-167-176-239.ngrok-free.app/crumbIssuer/api/json
         JENKINS_USER: admin
         JENKINS_TOKEN: bf0ca22f35774571aa00714e200bd3d7
       run: |
         # Fetch the Jenkins Crumb dynamically
         CRUMB=$(curl -s "$JENKINS_CRUMB_URL" \
           --user $JENKINS_USER:$JENKINS_TOKEN | jq -r '.crumb')
+        
         echo $CRUMB
        
-        # Ensure CRUMB was successfully fetched
-        if [ -z "$CRUMB" ]; then
-          echo "Failed to fetch Jenkins Crumb!"
-          exit 1
-        fi
+        # # Ensure CRUMB was successfully fetched
+        # if [ -z "$CRUMB" ]; then
+        #   echo "Failed to fetch Jenkins Crumb!"
+        #   exit 1
+        # fi
 
-        # Trigger the Jenkins job with the dynamically fetched Crumb
-        curl -X POST "$JENKINS_URL" \
-          --user $JENKINS_USER:$JENKINS_TOKEN \
-          -H "Jenkins-Crumb:$CRUMB" 
+        # # Trigger the Jenkins job with the dynamically fetched Crumb
+        # curl -X POST "$JENKINS_URL" \
+        #   --user $JENKINS_USER:$JENKINS_TOKEN \
+        #   -H "Jenkins-Crumb:$CRUMB" 
 
