Update Automation.yml

diff --git a/.github/workflows/Automation.yml b/.github/workflows/Automation.yml
--- a/.github/workflows/Automation.yml
+++ b/.github/workflows/Automation.yml
@@ -18,21 +18,33 @@ jobs:
         JENKINS_USER: admin
         JENKINS_TOKEN: bf0ca22f35774571aa00714e200bd3d7
       run: |
-        # Fetch the Jenkins Crumb dynamically
+        # Test crumb fetching
+        curl -s "$JENKINS_CRUMB_URL" \
+          --user $JENKINS_USER:$JENKINS_TOKEN | jq .
+
+        # Test triggering the build
         CRUMB=$(curl -s "$JENKINS_CRUMB_URL" \
           --user $JENKINS_USER:$JENKINS_TOKEN | jq -r '.crumb')
-        
-        echo "CRUMB value is :--- " $CRUMB
-       
-        # Ensure CRUMB was successfully fetched
-        if [ -z "$CRUMB" ]; then
-          echo "Failed to fetch Jenkins Crumb!"
-          exit 1
-        fi
 
-        # Trigger the Jenkins job with the dynamically fetched Crumb
-        curl -X POST "$JENKINS_URL" \
+        curl -v -X POST "$JENKINS_URL" \
           --user $JENKINS_USER:$JENKINS_TOKEN \
-            -H "Jenkins-Crumb:$CRUMB" \
-            --data-urlencode "param1=value1" \
-            --data-urlencode "param2=value2"
+          -H "Jenkins-Crumb:$CRUMB"
+
+        # # Fetch the Jenkins Crumb dynamically
+        # CRUMB=$(curl -s "$JENKINS_CRUMB_URL" \
+        #   --user $JENKINS_USER:$JENKINS_TOKEN | jq -r '.crumb')
+        
+        # echo "CRUMB value is :--- " $CRUMB
+       
+        # # Ensure CRUMB was successfully fetched
+        # if [ -z "$CRUMB" ]; then
+        #   echo "Failed to fetch Jenkins Crumb!"
+        #   exit 1
+        # fi
+
+        # # Trigger the Jenkins job with the dynamically fetched Crumb
+        # curl -X POST "$JENKINS_URL" \
+        #   --user $JENKINS_USER:$JENKINS_TOKEN \
+        #     -H "Jenkins-Crumb:$CRUMB" \
+        #     --data-urlencode "param1=value1" \
+        #     --data-urlencode "param2=value2"
